//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpSword.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpSword.Resource.CoreResource", typeof(CoreResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未提供接口名称.
        /// </summary>
        internal static string Action_ActionNameIsNullOrString {
            get {
                return ResourceManager.GetString("Action_ActionNameIsNullOrString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请求参数【{0}】未提交或未指定参数值.
        /// </summary>
        internal static string ActionBase_ArgumentNullErrorActionResult_Info {
            get {
                return ResourceManager.GetString("ActionBase_ArgumentNullErrorActionResult_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行:{0}.GetRequestDto()方法错误，请检查客户端上送的JSON数据包格式是否正确(比如必须传入的参数未传入或者数据类型错误).
        /// </summary>
        internal static string ActionBase_GetRequestDto_DeserializeObject_Error {
            get {
                return ResourceManager.GetString("ActionBase_GetRequestDto_DeserializeObject_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 绑定上送业务参数失败，请检查上送Data参数JSON格式是否正确(1.JSON本身格式是否正确，2.参数的数据类型是否正确，3.请查看详细错误日志).
        /// </summary>
        internal static string ActionBase_RequestDto_Null {
            get {
                return ResourceManager.GetString("ActionBase_RequestDto_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此次操作需要提交操作用户ID(UserId)和用户名(UserName)，请确保上传的参数包(Data)有UserId和UserName参数.
        /// </summary>
        internal static string ActionBase_RequiredUserIdAndUserName_Error {
            get {
                return ResourceManager.GetString("ActionBase_RequiredUserIdAndUserName_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidUserIdAndUserNameFun未定义.
        /// </summary>
        internal static string ActionBase_ValidUserIdAndUserNameFun_Null_Error {
            get {
                return ResourceManager.GetString("ActionBase_ValidUserIdAndUserNameFun_Null_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复添加接口配置，接口名称：{0}.
        /// </summary>
        internal static string ActionConfigCollection_Add_Exists {
            get {
                return ResourceManager.GetString("ActionConfigCollection_Add_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本号不能为空.
        /// </summary>
        internal static string ActionConfigCollection_Add_Version_NotNull {
            get {
                return ResourceManager.GetString("ActionConfigCollection_Add_Version_NotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全局(IAuthentication)校验未通过，系统拒绝访问.
        /// </summary>
        internal static string ActionRequestHander_AppKeyAuthentication {
            get {
                return ResourceManager.GetString("ActionRequestHander_AppKeyAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接口校验失败.
        /// </summary>
        internal static string ActionRequestHander_AppKeyAuthentication_Attribute {
            get {
                return ResourceManager.GetString("ActionRequestHander_AppKeyAuthentication_Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到Action接口:{0}.
        /// </summary>
        internal static string ActionRequestHander_NotFoundAction {
            get {
                return ResourceManager.GetString("ActionRequestHander_NotFoundAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接口系统设置了白名单，但是您的IP地址【{0}】不在白名单之列，系统拒绝访问.
        /// </summary>
        internal static string ActionRequestHander_WhiteIpRefuse {
            get {
                return ResourceManager.GetString("ActionRequestHander_WhiteIpRefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接口出现异常：错误描述：{0}，详情：{1}.
        /// </summary>
        internal static string ActionRequestHanderActionResult_Error {
            get {
                return ResourceManager.GetString("ActionRequestHanderActionResult_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上送参数解密失败.
        /// </summary>
        internal static string DECRYPT_REQUEST_FAIL {
            get {
                return ResourceManager.GetString("DECRYPT_REQUEST_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型：{0}错误，ActionType必须继承ActionBase抽象类.
        /// </summary>
        internal static string DefaultActionActivator_TypeError {
            get {
                return ResourceManager.GetString("DefaultActionActivator_TypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未提供接口名称.
        /// </summary>
        internal static string DefaultActionFactory_ActionNameIsNullOrString {
            get {
                return ResourceManager.GetString("DefaultActionFactory_ActionNameIsNullOrString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到Action接口:{0}.
        /// </summary>
        internal static string DefaultActionFactory_ActionNameNotFound {
            get {
                return ResourceManager.GetString("DefaultActionFactory_ActionNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接口方法:{0} , 类型：{1}，执行Execute()方法错误，详细信息：{2}.
        /// </summary>
        internal static string DefaultActionInvoker_ActionExecuteError {
            get {
                return ResourceManager.GetString("DefaultActionInvoker_ActionExecuteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加载接口错误，同名接口出现版本重复，请根据错误信息检查接口名称。接口名称：{0},接口类型：{1}，冲突接口类型：{2}，版本号：{3}.
        /// </summary>
        internal static string DefaultActionSelector_FoundMoreThenOneActionName {
            get {
                return ResourceManager.GetString("DefaultActionSelector_FoundMoreThenOneActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:{0},类型：{1},系统不允许Ajax请求.
        /// </summary>
        internal static string DefaultActionValidator_EnableAjaxRequest {
            get {
                return ResourceManager.GetString("DefaultActionValidator_EnableAjaxRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:{0}，类型：{1}，使用http请求方式错误，请使用：HTTP-{2}方式提交数据.
        /// </summary>
        internal static string DefaultActionValidator_HttpMethod {
            get {
                return ResourceManager.GetString("DefaultActionValidator_HttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:{0}，类型：{1}，已经被注销，无法继续提供接口服务.
        /// </summary>
        internal static string DefaultActionValidator_IsObsolete {
            get {
                return ResourceManager.GetString("DefaultActionValidator_IsObsolete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action:{0}，类型：{1}，需要使用https连接进行请求.
        /// </summary>
        internal static string DefaultActionValidator_RequireHttps {
            get {
                return ResourceManager.GetString("DefaultActionValidator_RequireHttps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到指定的视图引擎，视图引擎必须支持后缀:{0}.
        /// </summary>
        internal static string DefaultViewEngineManager_IViewEngine_NotFound0 {
            get {
                return ResourceManager.GetString("DefaultViewEngineManager_IViewEngine_NotFound0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到视图引擎，请最少注册一个实现IViewEngine的视图引擎.
        /// </summary>
        internal static string DefaultViewEngineManager_IViewEngine_NotFound1 {
            get {
                return ResourceManager.GetString("DefaultViewEngineManager_IViewEngine_NotFound1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误消息：{0}，详细异常：{1}.
        /// </summary>
        internal static string ErrorAction_ErrInfo {
            get {
                return ResourceManager.GetString("ErrorAction_ErrInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性值必须大于：{0}.
        /// </summary>
        internal static string GreaterThanAttribute_Error {
            get {
                return ResourceManager.GetString("GreaterThanAttribute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性值必须大于等于：{0}.
        /// </summary>
        internal static string GreaterThanOrEqualAttribute_Error {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualAttribute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 值取值范围为:{0}.
        /// </summary>
        internal static string InAttribute_Error {
            get {
                return ResourceManager.GetString("InAttribute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性值必须小于：{0}.
        /// </summary>
        internal static string LessThanAttribute_Error {
            get {
                return ResourceManager.GetString("LessThanAttribute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性值必须小于等于：{0}.
        /// </summary>
        internal static string LessThanOrEqualAttribute_Error {
            get {
                return ResourceManager.GetString("LessThanOrEqualAttribute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 集合不能空.
        /// </summary>
        internal static string NotEmptyAttribute_Error {
            get {
                return ResourceManager.GetString("NotEmptyAttribute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 值不能与属性{0}相等.
        /// </summary>
        internal static string NotEqualAttribute_Error {
            get {
                return ResourceManager.GetString("NotEqualAttribute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 属性:{0}未找到.
        /// </summary>
        internal static string NotEqualAttribute_Exc {
            get {
                return ResourceManager.GetString("NotEqualAttribute_Exc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 字段是必需的.
        /// </summary>
        internal static string NotNullAttribute_Error {
            get {
                return ResourceManager.GetString("NotNullAttribute_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接口：{0}，类型：{1}，输出方式错误，只允许使用：{2} 方式返回数据.
        /// </summary>
        internal static string ResponseFormatAttribute_ResponseFormat_Error {
            get {
                return ResourceManager.GetString("ResponseFormatAttribute_ResponseFormat_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 接口：{0} 特性路由不能包含{1}或者{2}字符.
        /// </summary>
        internal static string RoutePublisher_ForbiddenCharacter {
            get {
                return ResourceManager.GetString("RoutePublisher_ForbiddenCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已经添加了特性路由：{0}，当前接口：{1}({2})，冲突接口：{3}({4}).
        /// </summary>
        internal static string RoutePublisher_RouteAdded {
            get {
                return ResourceManager.GetString("RoutePublisher_RouteAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未找到任何APi接口视图模板，已经搜索路径：{0}{1}.
        /// </summary>
        internal static string View_Not_Exists {
            get {
                return ResourceManager.GetString("View_Not_Exists", resourceCulture);
            }
        }
    }
}
