/* **************************************************************************
 * <auto-generated>
 *     This code was generated by a tool.
 *     Runtime Version:<%:Environment.Version.Major %>.<%:Environment.Version.Minor %>.<%:Environment.Version.Build %>.<%:Environment.Version.Revision %>
 *     OperatingSystem:<%:Environment.OSVersion %>        
 *     Changes to this file may cause incorrect behavior and will be lost if
 *     the code is regenerated.
 * </auto-generated>
 * **************************************************************************/
<%@ Page Language="C#" %>
<%@ Assembly Name="SharpSword" %>
<%@ Assembly Name="SharpSword.DtoGenerator" %>
<%@ Assembly Name="Autofac" %>
<%@ Import Namespace="SharpSword" %>
<%@ Import Namespace="SharpSword.DtoGenerator" %>
<%@ Import Namespace="SharpSword.DtoGenerator.Actions" %>
<%@ Import Namespace="SharpSword.DtoGenerator.ViewModels" %>
<%@ Import Namespace="SharpSword.WebApi" %>
<%@ Import Namespace="System.Collections.Specialized" %>
<%@ Import Namespace="System.Collections" %>
<%@ Import Namespace="System.Collections.Generic" %>
<%@ Import Namespace="System.Web" %>
<%@ Import Namespace="System.Linq" %>

<script runat="server">
    public DtoViewModel DTO;
</script>

<%

    if (DTO.IsNull()) { return; }

    //待映射的SQL语句
    //var sqls = this.DTO.SQL.Split(new string[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries);

    //映射的对象属性集合
    //var properties = this.DTO.DtoType.GetPropertiesInfo();
 %>

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

<!--NewLine-->

namespace <%:this.DTO.Namespace %>
{
    /// <summary>
    /// Guid:<%:MD5.Encrypt(this.DTO.SQL).ToUpper() %>
    /// </summary>
    [Serializable]
    public class <%:this.DTO.ClassName %><%:this.DTO.Inherit %>
    {
        <% foreach (var p in DTO.Properties) { %>

        /// <summary>
        /// 
        /// </summary>
        public <%:p.TypeName %> <%:p.Name %> { get; set; }

        <%} %>
         
    }
}

